/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $EmMsg: typeof import('element-plus')['ElMessage']
  const $EmMsgBox: typeof import('@/lib/msgBox')['EmMessageBox']
  const util: typeof import('@/utils')
}
